import {
  Coffee,
  Contact,
  Github,
  Home,
  Instagram,
  Linkedin,
  MessageCircleMore,
  User,
} from 'lucide-react';
import { AvailableStack, Career, Education, NavMenu, Profile, Project, Stack } from './types';

export const NAV_MENUS: NavMenu[] = [
  {
    sort: 1,
    label: 'Home',
    icon: Home,
    href: '/',
  },
  {
    sort: 2,
    label: 'About',
    icon: User,
    href: '/about',
  },
  {
    sort: 3,
    label: 'Projects',
    icon: Coffee,
    href: '/projects',
  },
  {
    sort: 4,
    label: 'Contact',
    icon: Contact,
    href: '/contact',
  },
  {
    sort: 5,
    label: 'Guestroom',
    icon: MessageCircleMore,
    href: '/guestroom',
  },
];

export const STACKS: Stack[] = [
  { label: 'Node.js', imageUrl: '/svgs/nodejs.svg' },
  { label: 'React.js', imageUrl: '/svgs/reactjs.svg' },
  { label: 'Next.js', imageUrl: '/svgs/nextjs.svg' },
  { label: 'HTML5', imageUrl: '/svgs/html5.svg' },
  { label: 'CSS3', imageUrl: '/svgs/css3.svg' },
  { label: 'Bootstrap', imageUrl: '/svgs/bootstrap.svg' },
  { label: 'TailwindCSS', imageUrl: '/svgs/tailwind.svg' },
  { label: 'React Native', imageUrl: '/svgs/reactjs.svg' },
  { label: 'Vite', imageUrl: '/svgs/vite.svg' },
  { label: 'Redux', imageUrl: '/svgs/redux.svg' },
  { label: 'Zustand', imageUrl: '/svgs/zustand.svg' },
  { label: 'Axios', imageUrl: '/svgs/axios.svg' },
  { label: 'React Hook Form', imageUrl: '/svgs/react-hook-form.svg' },
  { label: 'Zod', imageUrl: '/svgs/zod.svg' },
  { label: 'Chakra UI', imageUrl: '/svgs/chakra.svg' },
  { label: 'Daisy UI', imageUrl: '/svgs/daisy.svg' },
  { label: 'Material UI', imageUrl: '/svgs/material.svg' },
  { label: 'Shadcn UI', imageUrl: '/svgs/shadcn.svg' },
  { label: 'JavaScript', imageUrl: '/svgs/js.svg' },
  { label: 'TypeScript', imageUrl: '/svgs/ts.svg' },
  { label: 'Express.js', imageUrl: '/svgs/express.svg' },
  { label: 'Prisma', imageUrl: '/svgs/prisma.svg' },
  { label: 'MySQL', imageUrl: '/svgs/mysql.svg' },
  { label: 'PostgreSQL', imageUrl: '/svgs/postgresql.svg' },
  { label: 'Firebase', imageUrl: '/svgs/firebase.svg' },
  { label: 'MQTT', imageUrl: '/svgs/mqtt.svg' },
  { label: 'Dart', imageUrl: '/svgs/dart.svg' },
  { label: 'Flutter', imageUrl: '/svgs/flutter.svg' },
  { label: 'Python', imageUrl: '/svgs/python.svg' },
  { label: 'Raspberry Pi', imageUrl: '/svgs/raspberry-pi.svg' },
  { label: 'Postman', imageUrl: '/svgs/postman.svg' },
];

export const getStack = (key: AvailableStack) => STACKS.find(x => x.label === key)!;

export const MY_PROFILE: Profile = {
  name: 'Nuzul H.',
  nickName: 'Nuzul',
  avatar: 'https://github.com/nuzulh.png',
  address: 'Banda Aceh, Indonesia 🇮🇩',
  status1: 'Working remotely',
  status2: 'Open for freelance project',
  description: 'Experienced Software Engineer with over 3 years of hands-on expertise designing and implementing innovative web & mobile applications especially in frontend side. Strong problem-solving skills and a commitment to staying current with emerging trends in web & mobile development.',
  socials: [
    { label: 'Linkedin', href: 'https://linkedin.com/in/nuzulh', icon: Linkedin },
    { label: 'GitHub', href: 'https://github.com/nuzulh', icon: Github },
    // { label: 'Instagram', href: 'https://instagram.com/nuzulhikam', icon: Instagram },
  ],
  skills: STACKS,
};

// TODO: backend integration using prisma & postgresql
export const MY_PROJECTS: Project[] = [
  {
    cname: 'nuzulh-dev',
    title: 'nuzulh.dev',
    description: 'My personal website built from scratch using several powerful & modern technology stacks. Due this website is using starter plan (free) cloud hosting and databases; Vercel, Neon Serverless Postgres, and Firebase, with certain limitations, sometimes an error will occur. Feel welcome to utilize this website as a point of reference, a wellspring of inspiration, or as a template, all in accordance with the provided license. The source code is at your disposal to suit your specific requirements. Should you find value in this resource, your consideration of leaving a rating is greatly appreciated.',
    isFeatured: true,
    sourceCodeUrl: 'https://github.com/nuzulh/nuzulh-dev',
    demoUrl: 'https://nuzulh-dev.vercel.app/',
    thumbnailUrl: '/images/nuzulh-dev-1.webp',
    imageUrls: [
      '/images/nuzulh-dev-1.webp',
      '/images/nuzulh-dev-2.webp',
      '/images/pagespeed-desktop.webp',
      '/images/pagespeed-mobile.webp',
      '/images/gtmetrix.webp',
    ],
    stacks: [
      getStack('Next.js'),
      getStack('TypeScript'),
      getStack('Shadcn UI'),
      getStack('TailwindCSS'),
      getStack('Prisma'),
      getStack('PostgreSQL'),
      getStack('Firebase'),
    ],
  },
  {
    cname: 'skpi-ft-usk',
    title: 'SKPI-FT-USK',
    description: 'An internal web application for managing student activities and approving certificates as requirements for college graduation. It has two roles; student and administrator. Student role is submitting activities and requesting certificates approval to administrator. Administrator role is approving student\'s requests. Additionally, students able to message administrator in realtime for supports. Furthermore, the app consists with "export to PDF" feature that summarize student activities.',
    isFeatured: true,
    thumbnailUrl: '/images/skpi-1.webp',
    imageUrls: [
      '/images/skpi-1.webp',
      '/images/skpi-2.webp',
      '/images/skpi-3.webp',
    ],
    stacks: [
      getStack('React.js'),
      getStack('TypeScript'),
      getStack('Chakra UI'),
      getStack('Express.js'),
      getStack('MySQL'),
    ],
  },
  {
    cname: 'rumah-bahasa',
    title: 'Rumah Bahasa',
    description: 'An online language learning platform. Has a dashboard for admin/teacher roles to manage class participants, as well as learning lessons in the form of videos equipped with discussion features so that there is interaction between students and teachers on each subject.',
    isFeatured: true,
    demoUrl: 'https://rumahbahasa.vercel.app',
    thumbnailUrl: '/images/rumah-bahasa.webp',
    imageUrls: ['/images/rumah-bahasa.webp'],
    stacks: [
      getStack('Next.js'),
      getStack('TypeScript'),
      getStack('Shadcn UI'),
      getStack('TailwindCSS'),
      getStack('Prisma'),
      getStack('PostgreSQL'),
    ],
  },
  {
    cname: 'listkol',
    title: 'ListKOL - Landing Page',
    description: 'A starter responsive landing page built with React (Typescript) and Tailwind CSS.',
    isFeatured: true,
    sourceCodeUrl: 'https://github.com/nuzulh/fe-listkol',
    demoUrl: 'https://listkol.vercel.app',
    thumbnailUrl: '/images/listkol-1.webp',
    imageUrls: [
      '/images/listkol-1.webp',
      '/images/listkol-2.webp',
      '/images/listkol-3.webp',
      '/images/listkol-4.webp',
    ],
    stacks: [
      getStack('React.js'),
      getStack('TypeScript'),
      getStack('Shadcn UI'),
      getStack('TailwindCSS'),
      getStack('Vite'),
    ],
  },
  {
    cname: 'campus-life',
    title: 'CampusLife',
    description: 'Basically this is a todo application for mobile platform with expanded features, especially for college students which has complex tasks assigned by their lecturer. Specifically, this app have integrated with a university data center which make their students easier to manage tasks based on subjects & schedules connected with the university data center. Students will get notification in their smartphone for reminder of a task.',
    isFeatured: true,
    sourceCodeUrl: 'https://github.com/nuzulh/campus-life',
    thumbnailUrl: '/images/campus-life.webp',
    imageUrls: ['/images/campus-life.webp'],
    stacks: [
      getStack('Dart'),
      getStack('Flutter'),
      getStack('Firebase'),
    ],
  },
  {
    cname: 'no-trash',
    title: 'NoTrash',
    description: 'A mobile application built with Flutter and Firebase. The main feature of this app is reporting a piled up rubbish around user, the report consists description, location address & map coordinate, and a picture of the rubbish. Each submitted report will notify users with "Officer" role. The report will be reviewed and confirmed by officer, then follow the maps submitted by reporter and handle the piled up rubbish in that location. After a report confirmed and handled, the officer will get some points linked to his account that will make him get benefits from his superiors.',
    isFeatured: false,
    sourceCodeUrl: 'https://github.com/nuzulh/NoTrashApp',
    thumbnailUrl: '/images/no-trash.webp',
    imageUrls: ['/images/no-trash.webp'],
    stacks: [
      getStack('Dart'),
      getStack('Flutter'),
      getStack('Firebase'),
    ],
  },
];

export const MY_CAREERS: Career[] = [
  {
    logoUrl: '/svgs/usk.svg',
    role: 'Programming Laboratory Assistant',
    companyLabel: 'ICT USK',
    companyFullName: 'ICT - Universitas Syiah Kuala',
    address: 'Banda Aceh, Indonesia 🇮🇩',
    fromDate: new Date('2021-08-01'),
    endDate: new Date('2021-12-01'),
    workMode: 'Part-time',
    workType: 'Remote',
    responsibilities: [
      'Assisting instructors at teaching the students with programming subjects.',
      'Scoring all the exams and the tasks that the instructor gives to the students.',
      'Monitoring student\'s demo projects.',
    ],
  },
  {
    logoUrl: '/svgs/kampus-merdeka.svg',
    role: 'Associated Data Scientist Assistant',
    companyLabel: 'Kampus Merdeka',
    companyFullName: 'Kampus Merdeka - KEMDIKBUD',
    address: 'Jakarta, Indonesia 🇮🇩',
    fromDate: new Date('2021-11-01'),
    endDate: new Date('2021-12-01'),
    workMode: 'Part-time',
    workType: 'Remote',
    responsibilities: [
      'Assisting instructor at teaching the students with Artificial Intelligence subject.',
      'Scoring all the exams and the tasks that the instructor gives to students',
      'Monitoring student\'s demo projects.',
    ],
  },
  {
    logoUrl: '/images/ate.jpeg',
    role: 'Frontend Web Developer',
    companyLabel: 'ATE',
    companyFullName: 'PT. Aceh Technology Enthusiast',
    address: 'Banda Aceh, Indonesia 🇮🇩',
    fromDate: new Date('2021-12-01'),
    endDate: new Date('2023-01-01'),
    workMode: 'Part-time',
    workType: 'Hybrid',
    responsibilities: [
      'Refactored the HTML, CSS, and JavaScript code of existing web pages to improve page loading speed.',
      'Implemented a user login system to allow for security and authentication.',
      'Used cross-browser compatibility techniques to ensure pages render the same across all browsers.',
      'Designed and built a new responsive website frontend layout.',
      'Developed custom JavaScript widgets to enhance UX.',
    ],
  },
  {
    role: 'Frontend Engineer',
    companyLabel: 'Ruramas',
    companyFullName: 'PT. Ruramas',
    address: 'Tangerang Selatan, Indonesia 🇮🇩',
    fromDate: new Date('2023-01-01'),
    endDate: new Date('2024-04-01'),
    workMode: 'Full-time',
    workType: 'Remote',
    responsibilities: [
      'Designed multiple websites utilizing HTML, CSS, JavaScript, and Typescript.',
      'Developed components and repackaged existing components for reuse using Typescript.',
      'Debugged and maintained websites with cross-browser compatibility issues.',
      'Debugged and maintained React Native project with cross-platform compatibility issues.',
      'Developed modern front-end user interfaces with ReactJS and React Native.',
      'Collaborated with back-end developers to implement RESTful API endpoints.',
      'Sometimes collaborated with the architect team to set up the deployment server.',
    ],
  },
  {
    logoUrl: '/images/machine-vision.png',
    role: 'Frontend Developer',
    companyLabel: 'Machine Vision',
    companyFullName: 'PT. Lanius Inovasi Indonesia',
    address: 'Malang, Indonesia 🇮🇩',
    fromDate: new Date('2024-01-01'),
    endDate: new Date('2024-05-01'),
    workMode: 'Freelance',
    workType: 'Remote',
    responsibilities: [
      'Build reusable code and libraries for future use.',
      'Ensure the technical feasibility of UI/UX designs.',
      'Revamp several existing components using ReactJS and Material UI.',
      'Bug fixing.',
    ],
  },
  {
    logoUrl: '/svgs/xcidic.svg',
    role: 'Frontend Developer',
    companyLabel: 'Xcidic',
    companyFullName: 'PT. Xcidic Teknologi Indonesia',
    address: 'Jakarta, Indonesia 🇮🇩',
    fromDate: new Date('2024-04-01'),
    workMode: 'Full-time',
    workType: 'Remote',
    responsibilities: [
      'Build internal project components template.',
      'Worked on a new version of a freelancer marketplace web application (sribu.com). As a frontend developer, I personally worked on the dashboard layout, header, sidebar, footer, and implemented best practice to enhance performance and SEO.',
      'Slicing UI with pixel perfect.',
      'Team working with agile development method.',
      'Problem solving and bug fixing.',
    ],
  },
];

export const MY_EDUCATIONS: Education[] = [
  {
    logoUrl: '/svgs/usk.svg',
    schoolLabel: 'USK',
    schoolFullName: 'Universitas Syiah Kuala',
    address: 'Banda Aceh, Indonesia 🇮🇩',
    level: 'Bachelor\'s degree',
    major: 'Computer Engineering, (S.T)',
    fromYear: 2019,
    endYear: 2023,
    score: 3.51,
    scoreMax: 4.00,
  },
];

export const COMMON_MESSAGE = {
  error: 'Oops, sorry! Something error occurred 🧐',
  errorService: 'I think some of our services have trouble 😔. Please try again later.',
};
