import { Career } from '../types';

export const MY_CAREERS: Career[] = [
  {
    logoUrl: '/svgs/usk.svg',
    role: 'Programming Laboratory Assistant',
    companyLabel: 'USK',
    companyFullName: 'Universitas Syiah Kuala',
    address: 'Banda Aceh, Indonesia 🇮🇩',
    fromDate: new Date('2021-08-01'),
    endDate: new Date('2021-12-01'),
    workMode: 'Part-time',
    workType: 'Remote',
    responsibilities: [
      'Assisted instructors in teaching programming subjects to students, providing additional support and clarification.',
      'Evaluated and graded student exams and assignments, offering constructive feedback to enhance learning outcomes.',
      'Supervised and provided guidance for student demo projects, ensuring alignment with course objectives.',
      'Facilitated hands-on coding sessions to reinforce practical application of programming concepts.',
      'Collaborated with instructors to develop and refine course materials, incorporating latest programming trends and best practices.',
    ],
  },
  {
    logoUrl: '/svgs/kampus-merdeka.svg',
    role: 'Associated Data Scientist Assistant',
    companyLabel: 'Kampus Merdeka',
    companyFullName: 'Kampus Merdeka - KEMDIKBUD',
    address: 'Jakarta, Indonesia 🇮🇩',
    fromDate: new Date('2021-11-01'),
    endDate: new Date('2021-12-01'),
    workMode: 'Part-time',
    workType: 'Remote',
    responsibilities: [
      'Assisted instructors in teaching Artificial Intelligence concepts to students, providing additional support and clarification.',
      'Evaluated and graded student exams and assignments, offering constructive feedback to enhance learning outcomes.',
      'Supervised and provided guidance for student demo projects, ensuring alignment with course objectives and industry standards.',
      'Facilitated hands-on workshops and coding sessions to reinforce practical application of AI concepts.',
      'Collaborated with instructors to develop and refine course materials, incorporating latest AI trends and technologies.',
    ],
  },
  {
    logoUrl: '/images/ate.jpeg',
    role: 'Frontend Web Developer',
    companyLabel: 'ATE',
    companyFullName: 'PT. Aceh Technology Enthusiast',
    address: 'Banda Aceh, Indonesia 🇮🇩',
    fromDate: new Date('2021-12-01'),
    endDate: new Date('2023-01-01'),
    workMode: 'Part-time',
    workType: 'Hybrid',
    responsibilities: [
      'Optimized HTML, CSS, and JavaScript code to significantly enhance page loading speed and overall performance.',
      'Designed and implemented a robust user authentication system, improving website security and user experience.',
      'Utilized advanced cross-browser compatibility techniques to ensure consistent rendering and functionality across all major browsers.',
      'Architected and developed a fully responsive, mobile-first frontend layout, enhancing user engagement across devices.',
      'Created and integrated custom JavaScript widgets and interactive elements to elevate user experience and interface functionality.',
      'Collaborated with the design team to implement pixel-perfect UI components, ensuring visual consistency and brand alignment.',
      'Implemented performance monitoring tools to identify and resolve bottlenecks, resulting in a 30% improvement in page load times.',
    ],
  },
  {
    role: 'Frontend Engineer',
    companyLabel: 'Ruramas',
    companyFullName: 'PT. Ruramas',
    address: 'Tangerang Selatan, Indonesia 🇮🇩',
    fromDate: new Date('2023-01-01'),
    endDate: new Date('2024-04-01'),
    workMode: 'Full-time',
    workType: 'Remote',
    responsibilities: [
      'Architected and implemented responsive, cross-browser compatible websites using HTML5, CSS3, JavaScript, and TypeScript.',
      'Engineered reusable, type-safe components with TypeScript, improving code maintainability and reducing development time.',
      'Resolved complex cross-browser compatibility issues, ensuring consistent user experience across different platforms.',
      'Optimized React Native applications for cross-platform performance, addressing platform-specific challenges.',
      'Crafted modern, intuitive user interfaces using ReactJS and React Native, enhancing overall user engagement.',
      'Integrated RESTful API endpoints in collaboration with backend developers, ensuring seamless data flow and functionality.',
      'Contributed to deployment processes, working alongside the architecture team to streamline and automate server setups.',
    ],
  },
  {
    logoUrl: '/images/machine-vision.png',
    role: 'Frontend Developer',
    companyLabel: 'Machine Vision',
    companyFullName: 'PT. Lanius Inovasi Indonesia',
    address: 'Malang, Indonesia 🇮🇩',
    fromDate: new Date('2024-01-01'),
    endDate: new Date('2024-05-01'),
    workMode: 'Freelance',
    workType: 'Remote',
    responsibilities: [
      'Developed reusable components and utility functions to enhance code maintainability and efficiency.',
      'Collaborated with UI/UX designers to ensure technical feasibility and optimal implementation of designs.',
      'Refactored and modernized existing components using ReactJS and Material UI, improving performance and user experience.',
      'Identified, diagnosed, and resolved complex bugs across the application, enhancing overall stability.',
      'Implemented responsive design principles to ensure seamless functionality across various devices and screen sizes.',
    ],
  },
  {
    logoUrl: '/svgs/xcidic.svg',
    role: 'Frontend Developer',
    companyLabel: 'Xcidic',
    companyFullName: 'PT. Xcidic Teknologi Indonesia',
    address: 'Jakarta, Indonesia 🇮🇩',
    fromDate: new Date('2024-04-01'),
    endDate: new Date('2024-08-01'),
    workMode: 'Full-time',
    workType: 'Remote',
    responsibilities: [
      'Developed and maintained a comprehensive internal project components template, enhancing code reusability and consistency across projects.',
      'Contributed to frontend development for a new version of a freelancer marketplace web application (sribu.com), focusing on implementing the dashboard layout, header, sidebar, and footer components.',
      'Implemented best practices to optimize performance and SEO, resulting in improved page load times and search engine rankings.',
      'Delivered pixel-perfect UI implementations, ensuring high-fidelity translation of designs into functional interfaces.',
      'Collaborated effectively within an agile development team, participating in sprint planning, daily stand-ups, and retrospectives.',
      'Demonstrated strong problem-solving skills, efficiently identifying and resolving complex bugs and technical issues.',
      'Contributed to code reviews and knowledge sharing sessions, promoting best practices and continuous improvement within the team.',
    ],
  },
  {
    logoUrl: '/images/yoripe.png',
    role: 'Frontend Developer',
    companyLabel: 'YoRipe',
    companyFullName: 'YoRipe Pte Ltd',
    address: 'Singapore 🇸🇬',
    fromDate: new Date('2024-08-01'),
    workMode: 'Full-time',
    workType: 'Remote',
    responsibilities: [
      'Developed and maintained a mobile application for Android and iOS using React Native.',
      'Integrated RESTful APIs and managed state using Redux and React Query.',
      'Optimized app performance and ensured smooth user experience across different devices.',
      'Collaborated with the backend team to define and consume API endpoints.',
      'Utilized native device features such as sharing, notifications, and more.',
      'Conducted thorough testing and debugging to ensure app stability and reliability.',
      'Participated in code reviews and implemented best practices for mobile development.',
      'Stayed updated with the latest trends and technologies in mobile app development.',
    ],
  },
];
